let aventura = "aventura"
let accion = "accion"
let comedia = "comedia"
let drama = "drama"
let ficcion = "ficcion"
let policial = "policial"
let romance = "romance"
let suspense = "suspense"
let terror = "terror"

let biblioteca2 = [
    
    {
        nombre: "Chronicle",
        fecha: "2012",
        duracion: "89 min",
        genero: "ficcion",
        genero2: "",
        portada: "https://www.ecartelera.com/carteles/4600/4659/002_m.jpg",
        url: "./Peliculas/Chronicle.avi"
    },
    {
        nombre: "Cuerpos Especiales",
        fecha: "2013",
        duracion: "123 min",
        genero: "comedia",
        genero2: "policial",
        portada: "https://pics.filmaffinity.com/Cuerpos_especiales-568346165-large.jpg",
        url: "./peliculas/cuerpos.especiales.avi",
    }, {
        nombre: "El Diario de Greg",
        fecha: "2010",
        duracion: "120 min",
        genero: "comedia",
        genero2: "",
        portada: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRr_ULxJG7n91vG0DZ-fiv4hJcrH8EdslSMyQ1zJWMtef4qjg3",
        url: "./peliculas/el.diario.de.greg..avi",
    },
    {
        nombre: "El Diario de Greg 2",
        fecha: "2011",
        duracion: "100 min",
        genero: "comedia",
        genero2: "",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcScTgEl-KuIQD27HJynaBJkM5IuJZMGg_Lc6wZCyr9Pt1NAActQ",
        url: "./peliculas/Diario.De.Greg.2.La.Ley.De.Rodrick.avi",
    },
    {
        nombre: "El Diario de Greg 3",
        fecha: "2012",
        duracion: "94 min",
        genero: "comedia",
        genero2: "",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTptFJe04jlGrH0TSa5LMiu7XU-LoWPflMzlbjpPp7fLjaiYDQK",
        url: "./peliculas/Diario.de.Greg.(3).Dias.de.perros.avi",
    },
    {
        nombre: "Niños Grandes",
        fecha: "2010",
        duracion: "102 min",
        genero: "comedia",
        genero2: "",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQFE2ul5BX68ZpcV4ZoCpVhF6q4GWPIwPaKM-b3od1TFuQh4ypV",
        url: "./peliculas/Niños.grandes.DVDRip.Xvid.Dual.AC3.5.1.para.SpanishRed.avi",
    },
    {
        nombre: "Misión Imposible 4",
        fecha: "2011",
        duracion: "138 min",
        genero: "accion",
        genero2: "",
        portada: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTQmDQReXcZtIB5qMkQLw1Rbbvd1kES6g1zm85d6WqcM_KzLT9c",
        url: "./peliculas/Mision.imposible-Protocolo.Fantasma(2011).(Spanish).DVD-Rip.DivX-AC3.by.elhobbyt.(emulesonic.com).avi",
    },
    {
        nombre: "Men In Black 3",
        fecha: "2012",
        duracion: "106 min",
        genero: "ficcion",
        genero2: "accion",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSoC68Pgf-Rbq37AppMAZgo4XbBJp2RlHwyrQidqKyv8fNMSSwN",
        url: "./Peliculas/Men.In.Black.3.(Los.Hombres.de.Negro.3)(2012).avi",
    },
    {
        nombre: "Los Increibles",
        fecha: "2004",
        duracion: "116 min",
        genero: "ficcion",
        genero2: "aventura",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRHF4foiSxyXalD_114hGuAEP9mNwZVxg0wx0cZnFIutmVenaRw",
        url: "./Peliculas/Los.Increibles.(Edicion.Especial).avi",
    },
    {
        nombre: "Soy el Numero Cuatro",
        fecha: "2011",
        duracion: "120 min",
        genero: "ficcion",
        genero2: "accion",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRH4oVJG6ubrChGokWlEmbPQlxi6haOGG1KCoDlWpFathPdKwSV",
        url: "./Peliculas/Soy.el.numero.cuatro.(Spanish.English).HDrip.XviD-AC3.by.Triki.(proteinicos.es).avi",
    },
    {
        nombre: "Silencio de Hielo",
        fecha: "2012",
        duracion: "119 min",
        genero: "suspense",
        genero2: "drama",
        portada: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEYH9JUFlSYh4hnDmZbHlTLAbNJngwydyLsCU7FFODB6zOLq0y",
        url: "./Peliculas/Silencio.de.hielo.(Spanish).HDrip.XviD-AC3.by.KaNyO.(hispashare.com).avi",
    },
    {
        nombre: "Silencio de Amor",
        fecha: "2011",
        duracion: "105 min",
        genero: "comedia",
        genero2: "drama",
        portada: "http://es.web.img2.acsta.net/medias/nmedia/18/84/90/27/19763280.jpg",
        url: "./Peliculas/Silencio.de.amor.(Spanish).DVD-Rip.XviD-AC3.by.elhobbyt.(emulesonic.com).avi",
    },
    {
        nombre: "Silencio en la Nieve",
        fecha: "2012",
        duracion: "114 min",
        genero: "drama",
        genero2: "suspense",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSz_s5LKxkbNQfujdkalxw_XNh63CVCTd7p9m7vBykLhpcCN-sc",
        url: "./Peliculas/.avi",
    },
    {
        nombre: "Sherlock Holmes 2",
        fecha: "2011",
        duracion: "129 min",
        genero: "suspense",
        genero2: "accion",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRy7xPf_jaPVF3cpmV_YSCbzm82yia1oAztSzvVns_tJtZzHX3e",
        url: "./Peliculas/Sherlock Holmes Juego de Sombras (Spanish) 2011 DVDRip Xvid Ac3 5.1 Amelina.avi",
    },
    {
        nombre: "Rocky 2",
        fecha: "1979",
        duracion: "120 min",
        genero: "accion",
        genero2: "",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQJg_S_UjsjslyuszHSIt5TNCfG77EmSnLSdz9ATfsFvMDxcJqm",
        url: "./Peliculas/Rocky.II.avi",
    },
    {
        nombre: "Rocky 3",
        fecha: "1982",
        duracion: "100 min",
        genero: "accion",
        genero2: "",
        portada: "http://es.web.img3.acsta.net/pictures/210/582/21058253_20131115155115957.jpg",
        url: "./Peliculas/Rocky.III.(Spanish.English).DVD-Rip.XviD-AC3.by.Calzoncilloman.(proteinicos.es).avi",
    },
    {
        nombre: "RoboCop",
        fecha: "1987",
        duracion: "103 min",
        genero: "ficcion",
        genero2: "accion",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSxJ89ZKNyMJhCDae1xX9xpoJBnS-JpPlIULCj-58qmfcHaSGPY",
        url: "./Peliculas/Robocop.-.Montaje.Del.Director.(Spanish.English).HDrip.XviD-AC3.by.Calzoncilloman.(proteinicos.es).avi",
    },
    {
        nombre: "Prometheus",
        fecha: "2012",
        duracion: "124 min",
        genero: "ficcion",
        genero2: "suspense",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS1k03NWg9o2KSGgMgAkz26v1lCVONjp84-Z-UOsNdWdmkPjMX8",
        url: "./Peliculas/Prometheus.2012.(Spanish.English).HDrip.XviD-AC3.by.rodosky.(proteinicos.es).avi",
    },
    {
        nombre: "Ocho Apellidos Vascos",
        fecha: "2014",
        duracion: "98 min",
        genero: "comedia",
        genero2: "romance",
        portada: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTRl6F9g3ctCIhA6_D0R6cCje5DUmKUOSCt9Jcaqguurzl5izOe",
        url: "./Peliculas/Ocho.apellidos.vascos(2014).(Spanish).DVD-Rip.XviD-AC3.by.elhobbyt.(emulesonic.com).avi",
    },
    {
        nombre: "Mandela del mito al hombre",
        fecha: "2014",
        duracion: "152 min",
        genero: "drama",
        genero2: "",
        portada: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUJd_pKC9Bah9cby0IBmIuWVB8qFQPo4N8n4hXhhe5HSWQbwsf",
        url: "./Peliculas/Mandela.del.mito.al.hombre(2013).avi",
    },
    {
        nombre: "Los Goonies",
        fecha: "1985",
        duracion: "115 min",
        genero: "aventura",
        genero2: "comedia",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTg2ECQIB3x6ryjJKlDea9uDp-ui5qChDa9U7I3itZgcc74mAXH",
        url: "./Peliculas/Los.Goonies.avi",
    },
    {
        nombre: "Los Vengadores",
        fecha: "2012",
        duracion: "144 min",
        genero: "ficcion",
        genero2: "accion",
        portada: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA7dOZps0m0FaNJahnOR0FTMyb9Pr9Xqbur7R21gK5b61fsY2O",
        url: "./Peliculas/Los Vengadores2012.avi",
    },
    {
        nombre: "Las Aventuras de Tintín",
        fecha: "2011",
        duracion: "107 min",
        genero: "aventura",
        genero2: "comedia",
        portada: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAL5A8c9fiJciZewkp9NR--ULPwCqx3OVOdUDYtxELpruk0ukJ",
        url: "./Peliculas/Las Aventuras de Tintín (El Secreto del Unicornio).2011.HDRip.AC3.Spanish.avi",
    },
    {
        nombre: "El Cuerpo",
        fecha: "2012",
        duracion: "110 min",
        genero: "suspense",
        genero2: "",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTjyiFdGXE6Cr8jfLvOR3eOMlvSxy2t-Y7273_OFQGCQUCKAqJE",
        url: "./Peliculas/el.cuerpo..avi",
    },
    {
        nombre: "El Lobo de Wall Street",
        fecha: "2013",
        duracion: "180 min",
        genero: "comedia",
        genero2: "policial",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQUTVMh8i1zwjLZMaS1B4vOKABJqqqMP0xKEKMjGSn27FPGqGuL",
        url: "./Peliculas/El.lobo.de.Wall.Street.(Spanish).HDrip.XviD-AC3.(exploradoresp2p.com).avi",
    },
    {
        nombre: "Gran Torino",
        fecha: "2008",
        duracion: "120 min",
        genero: "suspense",
        genero2: "drama",
        portada: "https://images-na.ssl-images-amazon.com/images/I/91cpBX3kNrL._SL1500_.jpg",
        url: "./Peliculas/gran.torino.avi",
    },
    {
        nombre: "Guerra Mundial Z",
        fecha: "2013",
        duracion: "123 min",
        genero: "terror",
        genero2: "suspense",
        portada: "https://i.blogs.es/c14f9c/guerra-20mundial-20z-202013-20world-20war-20z-20poster/450_1000.jpg",
        url: "./Peliculas/Guerra.Mundial.Z.(2013).avi",
    },
    {
        nombre: "Harry Potter 7.2",
        fecha: "2011",
        duracion: "130 min",
        genero: "aventura",
        genero2: "ficcion",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRI2nz1ni5PuMgzg7Uqdq6b6d4eFDmCLnBIcPDuqZdW9RDQztTD",
        url: "./Peliculas/Harry.Potter.y.las.Reliquias.de.la.Muerte.2ªParte.(2011).avi",
    },
    {
        nombre: "Iron Man",
        fecha: "2008",
        duracion: "126 min",
        genero: "accion",
        genero2: "ficcion",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT95Db6V4jzEkaZjnWEV5n0qHu1a2InkUgafj3lWQDRxQIxYvL3",
        url: "./Peliculas/Iron Man (Ironman) (2008).avi",
    },
    {
        nombre: "Iron Man 2",
        fecha: "2010",
        duracion: "124 min",
        genero: "accion",
        genero2: "ficcion",
        portada: "http://es.web.img2.acsta.net/medias/nmedia/18/77/46/75/20134299.jpg",
        url: "./Peliculas/Iron Man 2 (Ironman 2) (2010).avi",
    },
    {
        nombre: "La Escalera de Jacob",
        fecha: "1990",
        duracion: "116 min",
        genero: "terror",
        genero2: "suspense",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQzMJlHQaes4a_xNqRhhziakOSuby2qM-dtYRKg48_RjhBue_j2",
        url: "./Peliculas/La.Escalera.De.Jacob.Spanish.XviD.MP3.DVDRip.By.FreAk.TEAm.avi",
    },
]
localStorage.setItem("key", JSON.stringify(biblioteca2))
